// Package seal implements the document-13 wire contract. It provides confidentiality
// and authenticity, not authorization; callers must still check the live mandate.
package seal

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
)

const (
	JWSType = "newtype-delegation+jws"
	// ReceiptJWSType separates Nexus run receipts (schema ruling §4) from
	// delegation certificates signed by the same key: a receipt never
	// verifies as a certificate and vice versa.
	ReceiptJWSType = "newtype-run-receipt+jws"
	JWEType        = "newtype-sealed+jwe"
	maxSize        = 1 << 20
)

var (
	ErrOpen   = errors.New("invalid sealed credential")
	ErrConfig = errors.New("invalid sealing configuration")
	b64       = base64.RawURLEncoding.Strict()
)

func decode64(value string) ([]byte, error) {
	decoded, err := b64.DecodeString(value)
	if err != nil || b64.EncodeToString(decoded) != value {
		return nil, ErrOpen
	}
	return decoded, nil
}

func mac(key, data []byte) []byte {
	h := hmac.New(sha256.New, key)
	h.Write(data)
	return h.Sum(nil)
}

// Expand is exactly one HKDF-Expand block, without HKDF-Extract.
func Expand(prk, info []byte) []byte {
	data := append(append([]byte(nil), info...), 1)
	return mac(prk, data)
}

func Info(delegation, session string) []byte {
	return []byte("newtype-seal/v1|" + delegation + "|" + session)
}

type Deriver interface {
	Derive(context.Context, string, []byte) ([]byte, string, error)
}

type MasterDeriver struct{ master []byte }

func NewMasterDeriver(master []byte) (*MasterDeriver, error) {
	if len(master) < 32 {
		return nil, ErrConfig
	}
	return &MasterDeriver{master: append([]byte(nil), master...)}, nil
}

func (d *MasterDeriver) Derive(ctx context.Context, account string, info []byte) ([]byte, string, error) {
	if err := ctx.Err(); err != nil {
		return nil, "", err
	}
	if d == nil || len(d.master) < 32 || account == "" || strings.ContainsAny(account, "|\x00") || len(info) == 0 {
		return nil, "", ErrConfig
	}
	acct := mac(d.master, []byte("newtype-account/v1|"+account))
	digest := sha256.Sum256(append([]byte("newtype-account-key-id|"), acct...))
	return Expand(acct, info), "acct_" + hex.EncodeToString(digest[:6]), nil
}

type PublicKey struct {
	KID string `json:"kid"`
	Alg string `json:"alg"`
	X   string `json:"x"`
}

type Ed25519Signer struct {
	key ed25519.PrivateKey
	kid string
}

func NewEd25519Signer(key ed25519.PrivateKey, kid string) (*Ed25519Signer, error) {
	if len(key) != ed25519.PrivateKeySize || kid == "" || len(kid) > 128 {
		return nil, ErrConfig
	}
	// Reject malformed private keys whose public half does not match the seed.
	derived := ed25519.NewKeyFromSeed(key[:ed25519.SeedSize])
	if !hmac.Equal(derived, key) {
		return nil, ErrConfig
	}
	return &Ed25519Signer{key: append(ed25519.PrivateKey(nil), key...), kid: kid}, nil
}

func (s *Ed25519Signer) Keys() []PublicKey {
	return []PublicKey{{KID: s.kid, Alg: "EdDSA", X: b64.EncodeToString(s.key.Public().(ed25519.PublicKey))}}
}

type jwsHeader struct {
	Alg string `json:"alg"`
	KID string `json:"kid"`
	Typ string `json:"typ"`
}

func (s *Ed25519Signer) SignJWS(typ string, payload []byte) (string, error) {
	if s == nil || len(s.key) != ed25519.PrivateKeySize || (typ != JWSType && typ != ReceiptJWSType) || len(payload) > maxSize/2 {
		return "", ErrConfig
	}
	h, _ := json.Marshal(jwsHeader{"EdDSA", s.kid, typ})
	input := b64.EncodeToString(h) + "." + b64.EncodeToString(payload)
	return input + "." + b64.EncodeToString(ed25519.Sign(s.key, []byte(input))), nil
}

// decodeHeader accepts only the exact header generated by this protocol. This
// rejects duplicate/unknown keys, alternate serialization and algorithm confusion.
func decodeHeader(encoded string, dst any) bool {
	raw, err := decode64(encoded)
	if err != nil || len(raw) > 4096 || json.Unmarshal(raw, dst) != nil {
		return false
	}
	canonical, err := json.Marshal(dst)
	return err == nil && string(raw) == string(canonical) && b64.EncodeToString(raw) == encoded
}

func Verify(jws string, keys []PublicKey) ([]byte, error) { return VerifyType(jws, keys, JWSType) }

// VerifyType is Verify for one exact JWS type.
func VerifyType(jws string, keys []PublicKey, typ string) ([]byte, error) {
	if len(jws) > maxSize || (typ != JWSType && typ != ReceiptJWSType) {
		return nil, ErrOpen
	}
	parts := strings.Split(jws, ".")
	if len(parts) != 3 {
		return nil, ErrOpen
	}
	var h jwsHeader
	if !decodeHeader(parts[0], &h) || h.Alg != "EdDSA" || h.Typ != typ || h.KID == "" {
		return nil, ErrOpen
	}
	var public []byte
	for _, k := range keys {
		if k.KID != h.KID {
			continue
		}
		if public != nil || k.Alg != "EdDSA" {
			return nil, ErrOpen
		}
		var err error
		public, err = decode64(k.X)
		if err != nil || len(public) != ed25519.PublicKeySize {
			return nil, ErrOpen
		}
	}
	payload, err := decode64(parts[1])
	if err != nil {
		return nil, ErrOpen
	}
	sig, err := decode64(parts[2])
	if err != nil || len(public) != ed25519.PublicKeySize || !ed25519.Verify(public, []byte(parts[0]+"."+parts[1]), sig) {
		return nil, ErrOpen
	}
	return payload, nil
}

type Sealer struct {
	Signer  *Ed25519Signer
	Deriver Deriver
}

type Sealed struct {
	Sealed string `json:"sealed"`
	Key    []byte `json:"key"`
	KID    string `json:"kid"`
}

type jweHeader struct {
	Alg string `json:"alg"`
	Enc string `json:"enc"`
	KID string `json:"kid"`
	Typ string `json:"typ"`
	Cty string `json:"cty"`
}

func (s *Sealer) Seal(ctx context.Context, account, delegation, session string, payload []byte) (Sealed, error) {
	if s == nil || s.Signer == nil || s.Deriver == nil || delegation == "" || session == "" || strings.ContainsAny(delegation+session, "|:\x00") {
		return Sealed{}, ErrConfig
	}
	jws, err := s.Signer.SignJWS(JWSType, payload)
	if err != nil {
		return Sealed{}, err
	}
	key, kid, err := s.Deriver.Derive(ctx, account, Info(delegation, session))
	if err != nil {
		return Sealed{}, err
	}
	if len(key) != 32 || kid == "" || strings.Contains(kid, ":") {
		return Sealed{}, ErrConfig
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return Sealed{}, ErrConfig
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return Sealed{}, ErrConfig
	}
	h, _ := json.Marshal(jweHeader{"dir", "A256GCM", kid + ":" + delegation + ":" + session, JWEType, "JWT"})
	protected := b64.EncodeToString(h)
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return Sealed{}, err
	}
	ct := gcm.Seal(nil, nonce, []byte(jws), []byte(protected))
	n := len(ct) - gcm.Overhead()
	return Sealed{protected + ".." + b64.EncodeToString(nonce) + "." + b64.EncodeToString(ct[:n]) + "." + b64.EncodeToString(ct[n:]), append([]byte(nil), key...), kid}, nil
}

func Open(sealed string, key []byte) (string, string, error) {
	if len(sealed) > maxSize*2 || len(key) != 32 {
		return "", "", ErrOpen
	}
	p := strings.Split(sealed, ".")
	if len(p) != 5 || p[1] != "" {
		return "", "", ErrOpen
	}
	var h jweHeader
	if !decodeHeader(p[0], &h) || h.Alg != "dir" || h.Enc != "A256GCM" || h.Typ != JWEType || h.Cty != "JWT" {
		return "", "", ErrOpen
	}
	ids := strings.Split(h.KID, ":")
	if len(ids) != 3 || ids[0] == "" || ids[1] == "" || ids[2] == "" {
		return "", "", ErrOpen
	}
	nonce, e1 := decode64(p[2])
	ct, e2 := decode64(p[3])
	tag, e3 := decode64(p[4])
	if e1 != nil || e2 != nil || e3 != nil || len(nonce) != 12 || len(tag) != 16 {
		return "", "", ErrOpen
	}
	block, _ := aes.NewCipher(key)
	gcm, _ := cipher.NewGCM(block)
	plain, err := gcm.Open(nil, nonce, append(ct, tag...), []byte(p[0]))
	if err != nil {
		return "", "", ErrOpen
	}
	return string(plain), h.KID, nil
}
